home/workspace/cy/cy/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('world/', include('world.urls')),
    path('accounts/', include('allauth.urls')),
]

home/workspace/cy/world/urls.py
from django.urls import path
from . import views

app_name="world"
urlpatterns=[
    path('visitor/', views.visitor, name="visitor"),
    path('gallery/', views.gallery, name="gallery"),
    path('create/', views.create, name="create"),
    path('new/', views.new, name="new"), #여기 추가함
    path('<int:id>/', views.show, name="show"), #여기 추가함
    path('<int:id>/new_comment/', views.new_comment, name="new_comment"),
    path('<int:id>/create_comment/', views.create_comment, name="create_comment"),
    path('<int:id>', views.delete, name="delete"),
    path('<int:id>', views.delete_comment, name="delete_comment"),
    path('favourite/', views.favourite, name="favourite"),
    path('<int:id>/like/', views.like, name="like"),
]

home/workspace/cy/world/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User



class Post(models.Model):
    objects = models.Manager()
    title = models.CharField(max_length=200)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    likes = models.ManyToManyField(User, related_name='likes')
       

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
 
# Create your models here.

class Comment(models.Model):
    objects = models.Manager()
    content = models.TextField()
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name='comments')
    
    created_at = models.DateTimeField(auto_now_add=True)

home/workspace/cy/world/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'content'
        ]
        labels = {
            'title': "제목",
            'content': "내용"
        }
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'content',
        ]
        labels = {
            'content': "내용",
        }

home/workspace/cy/cy/views.py
from django.shortcuts import render
# from world .models import world

def home(request):
    return render(request, 'home.html')

home/workspace/cy/world/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .forms import PostForm, CommentForm
from .models import Post, Comment
from django.contrib.auth.models import User

def visitor(request):
    posts = Post.objects.all()
    return render(request, 'world/visitor.html', {"posts":posts})
    
def gallery(request):
    return render(request, 'world/gallery.html')

def create(request):
    return render(request, 'world/create.html')
    
def new(request):
    form = PostForm()
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False) # form을 당장 저장하지 않음. 데이터 저장 전 뭔가 하고 싶을 때 사용.
            form.user = request.user
            form.save()
            return redirect('world:visitor')
    return render(request, 'world/new.html', {'form': form})
    
    
    

    
def show(request, id):
    post = get_object_or_404(Post, pk=id)
    return render(request, 'world/show.html', {"post": post})
    
def update(request, id):
    post = get_object_or_404(Post, pk=id)
    if request.method == "POST":
        title = request.POST.get('title')
        content = request.POST.get('content')
        post.title = title
        post.content = content
        post.save()
        return redirect('world:show', post.id)
    return render(request, 'world/update.html', {"post": post})
    
def delete(request, id):
     post = get_object_or_404(Post, pk=id)
     post.delete()
     return redirect('world:visitor')
    
# Comment

def create_comment(request, id):
    form = CommentForm()
    post = get_object_or_404(Post, pk=id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
            return redirect('world:show', post.id)
    return render(request, 'world/new_comment.html', {'form': form})
    

def new_comment(request, id):
    post = get_object_or_404(Post, pk=id)
    return render(request, 'world/new_comment.html', {'post': post})
    
def delete_comment(request, id):
    comment = get_object_or_404(Comment, pk=id)
    post = comment.post
    comment.delete()
    return redirect('world:show', post.id)
    
# Like

def favourite(request):
    return render(request, 'world/favourite.html')
    


def like(request, id):
    user = request.user #로그인한 유저를 가져옴
    post = get_object_or_404(Post, pk=id)  #넘겨받은 id값을 다시Post에 넘겨줘서 id를 찾도록
    if request.method == 'POST':
        if post.likes.filter(id = user.id).exists(): #해당 post에 로그인한 유저가 like 컬럼에 존재하면
            post.likes.remove(user) #like 컬럼에서 해당 유저를 지운다. 즉 이미 좋아요를 눌렀는지 안눌렀는지 찾고 눌렀다면 지워줌(좋아요 취소)
        else:
            post.likes.add(user) #그 외의 경우 추가한다.
    return redirect('world:show', post.id) 
    

home/workspace/cy/templates/base.html
{% load static from staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- 아래 한 줄 코드 추가 -->
    <link rel="stylesheet" href="{% static 'css/project.css' %}">
     <style type="text/css">
      	@font-face { font-family: 'UhBeeMiMi'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_five@.2.0/UhBeeMiMi.woff') format('woff'); font-weight: normal; font-style: normal; }
          
          body{
            display: flex;
            justify-content: center;
            background: RGB(136,136,136);
            text-align: center;
            font-family:'UhBeeMiMi';
            font-size:10px; 
          }
          .con{
            border-radius: 25px;
            flex-wrap: wrap;
      		  align-content: center;
      		  margin-top : 100px;
            display: flex;
            background: RGB(142,215,230);
            width:1000px;
            height:600px;
            flex-direction: column;
          }
          .con_{
            border-radius: 25px;
            flex-wrap: wrap;
      		  align-content: center;
      		  margin-top : 27px;
            display: flex;
            background: RGB(232,233,232);
            width:900px;
            height:550px;
            flex-direction: column;
            border-style: dotted;
            border-color: RGB(152,229,242);
            padding:30px;
          }
          .button{
             border-radius: 5px;
              width:60px;
              margin-top : 7px;
              background-color:  RGB(142,215,230);
              color: black;
              height:30px;
              font-size: 12px;
              cursor: pointer;
              border-color: RGB(142,215,230);
              color: white;
              padding-top:4px;
            
          }
            
            
            .button:hover {
              background-color: white;
              color: black;
            }
            
          
      </style>
  </head>
  <body>
 <!-- 아래 두 줄 코드 추가 -->
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script>
      $(function () {
        $('[data-toggle="popover"]').popover()
      })
    </script>
  </body>
</html>

home/workspace/cy/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style type="text/css">
    .fir{
        width:300px;
        height:500px;
        flex-direction: column;
        background:white;
        border-radius: 25px;
        padding:30px;
    }  	
    .sec{
        width:500px;
        height:500px;
        display:flex;
        flex-direction:column;
        
        justify-content: flex-start;
        background:white;
        border-radius: 25px;
        padding-top:40px;
        font-size:10px;
    }
    .secc>p{
        margin-left:10px;
    }
    
    .fir > p{
        font-size:20px;
    }
    .secc{
        text-align: left;
        display:flex;
        flex-direction:column;
        justify-content: flex-start;
        background:white;
        
        margin-left:25px;
        font-size:14px;
    }
    
          
          
</style>
      
      
{% if user.is_authenticated %}     
<div class= con>
    <div class= con_>
        <div class=fir>
            <img id="prof" src="/static/image/prof.jpg" width="150" >
            <p><br><br><br><br>난 지금 미쳐가고 있다<br>이 헤드폰에 내 모든 몸과<br> 영혼을 잃었다.<br>음악만이 나라에서 허락하는<br>유일한 마약이니까<br></p>
        </div>
        <div class=sec>
            
            <div class=secc>
                <img id="gae" src="/static/image/gae.PNG" width="60" >
                
                <a href="{% url 'world:gallery' %}">난 가끔...</a>
                <a href="{% url 'world:gallery' %}">Americano...</a>
                <a href="{% url 'world:gallery' %}">눈물 is...</a>
            </div>
                <img id="mini" src="/static/image/mini.PNG" width="450" >
            
        </div>
        
        <a href="{% url 'home' %}"><div class=button>
            <p>Home</p>
        </div> </a>
        <a href="{% url 'world:visitor' %}"><div class=button>
            <p>Visitor</p>
        </div></a>
        <a href="{% url 'world:gallery' %}"><div class=button>
            <p>Gallery</p>
        </div></a>
    </div>
</div>


{% else %}
<div class= con>
    <div class= con_>
        <div class=fir>
            <img id="prof" src="/static/image/prof.jpg" width="150" >
            <p><br><br><br><br><br><br>난 지금 미쳐가고 있다<br>이 헤드폰에 내 모든 몸과<br> 영혼을 잃었다.<br>음악만이 나라에서 허락하는<br>유일한 마약이니까<br></p>
        </div>
        <div class=sec>
            
            <img id="mini" src="/static/image/mini.PNG" width="450" >
        </div>
        <a href="{% url 'account_login' %}"><div class=button>
            <p>login</p>
        </div> </a>
       
    </div>
</div>

{% endif %}
{% endblock %}

home/workspace/cy/world/templates/world/create.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style type="text/css">
    .fir{
        width:300px;
        height:500px;
        flex-direction: column;
        background:white;
        border-radius: 25px;
        padding:30px;
    }  	
    .sec{
        width:500px;
        height:500px;
        flex-direction: column;
        background:white;
        border-radius: 25px;
        padding :30px;
    }
    .fir > p{
        font-size:20px;
    }
          
    .can{
        width :400px;
        height :200px;
    }     
          
</style>
      
   
<div class= con>
    <div class= con_>
        <div class=fir>
            <img id="prof" src="/static/image/prof.jpg" width="150" >
            <p><br><br><br><br>난 지금 미쳐가고 있다<br>이 헤드폰에 내 모든 몸과<br> 영혼을 잃었다.<br>음악만이 나라에서 허락하는<br>유일한 마약이니까<br></p>
        </div>
        <div class=sec>
            
            <form action="{% url 'world:new' %}" method="POST">
                {% csrf_token %}
                
                <label width="100">글의 제목</label><br>
                <input type="text" name="title"><br>
                
                <label>글의 내용</label><br>
                <textarea name="content"></textarea><br>
                
                <input type="submit" value="글쓰기">
            </form>
        </div>
        
        <a href="{% url 'home' %}"><div class=button>
            <p>Home</p>
        </div> </a>
        <a href="{% url 'world:visitor' %}"><div class=button>
            <p>Visitor</p>
        </div></a>
        <a href="{% url 'world:gallery' %}"><div class=button>
            <p>Gallery</p>
        </div></a>
    </div>
</div>



{% endblock %}


               

home/workspace/cy/world/templates/world/gallery.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style type="text/css">
    .fir{
        width:300px;
        height:500px;
        flex-direction: column;
        background:white;
        border-radius: 25px;
        padding:30px;
    }  	
    .sec{
        width:500px;
        height:500px;
        flex-direction: column;
        background:white;
        border-radius: 25px;
        padding :15px,30px,0px,30px;
        justify-content:flex-end;
        overflow:auto;
    }
    .fir > p{
        font-size:20px;
    }
    
    .post{
       font-size:20px;
       padding-left : 30px;
       padding-right : 30px;
       padding-top:15px;
       flex-direction: column;
       
       
     } 
     
     .comment{
         font-size:15px;
         padding-left:30px;
         background:white;
         display:flex;
          justify-content:flex-start;
     } 
     .name{
         background:RGB(228,229,223);
         display:flex;
         font-weight: bold;
         justify-content:center;
         font-size:20px;
         padding :5px;
         
     }
     img{
         margin-right:20px;
     }
     button{
         display:flex;
         justify-content:center;
         width:55px;
         font-size:15px;
         margin-left:400px;
         margin-top:10px;
     }
          
</style>
      
      
  
<div class= con>
    <div class= con_>
        <div class=fir>
            <img id="prof" src="/static/image/prof.jpg" width="150" >
            <p><br><br><br><br>난 지금 미쳐가고 있다<br>이 헤드폰에 내 모든 몸과<br> 영혼을 잃었다.<br>음악만이 나라에서 허락하는<br>유일한 마약이니까<br></p>
        </div>
        <div class=sec>
                 
                  <div class = post>
                      <p class = name><b>난 가끔..</b></p>
                       <img id="chae" src="/static/image/chae.PNG" width="300px" >
                       <br><br>
                       <p>난... ㄱ ㅏ끔...<br> 눈물을 흘린 ㄷ  ㅏ....
                       <br>ㄱ  ㅏ끔은 눈물을 참을 수 없는 ㄴ  ㅐ가 별루다...
                       <br>소 ㄹ ㅣ치며... 울 수 있 ㄷ ㅏ는건...<br>
                       좋은 ㄱ ㅓ 야 ....
                       <br> 머리ㄱ r ㅇ  r ㄴ  iㄴ 맘으로.. 우는,,,
                       <br> ㄴ  ㅐ 가  좋..ㄷ r..☆</p>
                    
                   </div>
                   
                  <div class = post>
                      <p class = name><b>Americano,,,</b></p>
                       <img id="jang" src="/static/image/jang.PNG" width="400px" >
                       <br><br>
                       <p>따듯한 커피를 시키고<br> 사진을 찍고 수없이 메모를 하며
                       <br>어느새 네 번이나 리필을 하는 그의 모습은
                       <br>염치가 없다기보다는 그만의 여유를 한없이 즐기는 것 같아 보인다<br>
                      <br><br> 그게 바로 지금의 내 모습이다</p>
                    
                   </div>
                   
                   <div class = post>
                      <p class = name><b>눈물..is..</b></p>
                       <img id="moon" src="/static/image/moon.PNG" width="400px" >
                       <br><br>
                       <p>눈물을 흘릴줄 아는 사람이 아름답다.<br> 이모 생각이 나서 너무 보고싶어서...
                       <br>눈물이.....쏟아져....
                       <br>보이나요 나의 눈물이..<br>보이나요 나의 한숨이..
                      <br>하늘까지 닿을수만 있다면..</p>
                    
                   </div>
                    
            
        </div>
        <a href="{% url 'home' %}"><div class=button>
            <p>Home</p>
        </div> </a>
        <a href="{% url 'world:visitor' %}"><div class=button>
            <p>Visitor</p>
        </div></a>
        <a href="{% url 'world:gallery' %}"><div class=button>
            <p>Gallery</p>
        </div></a>
    </div>
</div>



{% endblock %}

home/workspace/cy/world/templates/world/new_comment.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style type="text/css">
    .fir{
        width:300px;
        height:500px;
        flex-direction: column;
        background:white;
        border-radius: 25px;
        padding:30px;
    }  	
    .sec{
        width:500px;
        height:500px;
        flex-direction: column;
        background:white;
        border-radius: 25px;
        padding :30px;
    }
    .fir > p{
        font-size:20px;
    }
          
          
          
</style>
      
   
<div class= con>
    <div class= con_>
        <div class=fir>
            <img id="prof" src="/static/image/prof.jpg" width="150" >
            <p><br><br><br><br>난 지금 미쳐가고 있다<br>이 헤드폰에 내 모든 몸과<br> 영혼을 잃었다.<br>음악만이 나라에서 허락하는<br>유일한 마약이니까<br></p>
        </div>
        <div class=sec>
            
            <form action="{% url 'world:create_comment' post.id %}" method="POST">
                {% csrf_token %}
                <label>댓글 내용</label><br>
                <textarea name="content"></textarea><br>
                
                <input type="submit" value="댓글쓰기">
            </form>
        </div>
        
        <a href="{% url 'home' %}"><div class=button>
            <p>Home</p>
        </div> </a>
        <a href="{% url 'world:visitor' %}"><div class=button>
            <p>Visitor</p>
        </div></a>
        <a href="{% url 'world:gallery' %}"><div class=button>
            <p>Gallery</p>
        </div></a>
    </div>
</div>



{% endblock %}

home/workspace/cy/world/templates/world/show.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style type="text/css">
    .fir{
        width:300px;
        height:500px;
        flex-direction: column;
        background:white;
        border-radius: 25px;
        padding:30px;
    }  	
    .sec{
        width:500px;
        height:500px;
        flex-direction: column;
        background:white;
        border-radius: 25px;
        padding :15px,30px,0px,30px;
        justify-content:flex-end;
    }
    .fir > p{
        font-size:20px;
    }
    
    .post{
       font-size:15px;
       padding-left : 30px;
       padding-right : 30px;
       padding-top:15px;
       flex-direction: row;
       justify-content:flex-start;
       
     } 
     .comment{
         font-size:15px;
         padding-left:30px;
         background:white;
         display:flex;
          justify-content:flex-start;
     } 
     .name{
         background:RGB(228,229,223);
         display:flex;
         justify-content:flex-start;
         justify-content:space-between;
         font-size:15px;
         padding :3px;
         padding-left:20px;
         padding-right:20px;
         
     }
     img{
         margin-right:20px;
     }
     .like{
         display:flex;
         flex-direction: row;
         
     }
     .like > p{
        margin-left:150px;
     }
     
          
</style>
      
      
  
<div class= con>
    <div class= con_>
        <div class=fir>
            <img id="prof" src="/static/image/prof.jpg" width="150" >
            <p><br><br><br><br>난 지금 미쳐가고 있다<br>이 헤드폰에 내 모든 몸과<br> 영혼을 잃었다.<br>음악만이 나라에서 허락하는<br>유일한 마약이니까<br></p>
        </div>
        <div class=sec>
            
              
                 
                  <div class = post>
                      
                    <div class=name>No. {{ post.id }}      .      {{ post.user }} 
                        <form action="{% url 'world:delete' post.id %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" value="삭제"> 
                        </form></div><br>
                    
                        <p class=comment><img id="visitor" src="/static/image/visitor.PNG" width="100" ><br>{{ post.content }}</p>
                   
                    <div class=like>
                        <form action="{% url 'world:like' post.id%}" method="POST">
                            {% csrf_token %}
                            <input type="image" src="/static/image/heart.png" width="30"  alt="Submit Form">
                        </form>
                       
                        <a href="{% url 'world:new_comment' post.id %}"><img id="com" src="/static/image/com.png" height="30" ></a>
                         {% for user in post.likes.all %}
                          <p data-container="body" data-toggle="popover" data-placement="top" data-content= {{ user.username }}, > ♥ {{ post.likes.count }}</p>
                        {% empty %}
                        
                        {% endfor %}
                    </div>
                   
                    
                        
                        
                        
                   
                    {% for comment in post.comments.all %}
                        <div class=name>{{ comment.user }} : {{ comment.content }}
                        <form action="{% url 'world:delete_comment' comment.id %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" value="댓글삭제">
                        </form>
                        </div>
                        {% empty %}
                        
                    {% endfor %}
                   </div>
                   
                
            
        </div>
        <a href="{% url 'home' %}"><div class=button>
            <p>Home</p>
        </div> </a>
        <a href="{% url 'world:visitor' %}"><div class=button>
            <p>Visitor</p>
        </div></a>
        <a href="{% url 'world:gallery' %}"><div class=button>
            <p>Gallery</p>
        </div></a>
    </div>
</div>


{% endblock %}

home/workspace/cy/world/templates/world/visitor.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style type="text/css">
    .fir{
        width:300px;
        height:500px;
        flex-direction: column;
        background:white;
        border-radius: 25px;
        padding:30px;
    }  	
    .sec{
        width:500px;
        height:500px;
        flex-direction: column;
        background:white;
        border-radius: 25px;
        padding :15px,30px,0px,30px;
        justify-content:flex-end;
        overflow:auto;
    }
    .fir > p{
        
        font-size:20px;
    }
    
    .post{
       font-size:15px;
       padding-left : 30px;
       padding-right : 30px;
       padding-top:15px;
       flex-direction: row;
       justify-content:flex-start;
       
     } 
     .comment{
         font-size:15px;
         padding-left:30px;
         background:white;
         display:flex;
          justify-content:flex-start;
     } 
     .name{
         background:RGB(228,229,223);
         display:flex;
         justify-content:flex-start;
         font-size:15px;
         padding :3px;
         
     }
     img{
         margin-right:20px;
     }
     button{
         display:flex;
         justify-content:center;
         width:55px;
         font-size:15px;
         margin-left:400px;
         margin-top:10px;
     }
          
</style>
      
      
  
<div class= con>
    <div class= con_>
        <div class=fir>
            <img id="prof" src="/static/image/prof.jpg" width="150" >
            <p><br><br><br><br>난 지금 미쳐가고 있다<br>이 헤드폰에 내 모든 몸과<br> 영혼을 잃었다.<br>음악만이 나라에서 허락하는<br>유일한 마약이니까<br></p>
        </div>
        <div class=sec>
            <a href="{% url 'world:create' %}"><button>글쓰기</button></a>
              {% for post in posts %}
                 
                  <div class = post>
                      
                    <a href="{% url 'world:show' post.id %}"><p class=name>No. {{ post.id }}    {{ post.user }} </p></a>
                    
                    
                        <p class=comment><img id="visitor" src="/static/image/visitor.PNG" width="100" ><br>{{ post.content }}</p>
                    
                   </div>
                    {% empty %}
                    <p>글이 없습니다.</p>
                {% endfor %}
            
        </div>
        <a href="{% url 'home' %}"><div class=button>
            <p>Home</p>
        </div> </a>
        <a href="{% url 'world:visitor' %}"><div class=button>
            <p>Visitor</p>
        </div></a>
        <a href="{% url 'world:gallery' %}"><div class=button>
            <p>Gallery</p>
        </div></a>
    </div>
</div>



{% endblock %}